seed: 1
torch_deterministic: true
cuda: true
track: true
wandb_project_name: "MultiGrid"
wandb_entity: "rl-power"
capture_video: false

total_timesteps: 1000000
learning_rate: 0.00025
num_envs: 1
num_steps: 128
anneal_lr: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
norm_adv: true
clip_coef: 0.2
clip_vloss: true
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null

# These will be computed at runtime
batch_size: 0
minibatch_size: 0
num_iterations: 0

# Logistics params
save_model_episode: 10000
visualize_every: 10000  # how many episodes before making a video
log_episode: 500
log_step: 1000
version: "default"
print_every: 10
base_save_path: ''

# Loss weights
dqn_loss_weight: 1

# architecture
fc_direction: 8
cumulants: 64
filters: 32
kernel_size: 3
fc: 256